alias gti='git'
#alias tmux='tmux -2'
alias less='less -R'
alias diff='colordiff'
alias dc='cd'
alias nethack-online='ssh nethack@nethack.alt.org ; clear'
alias tron-online='ssh sshtron.zachlatta.com ; clear'
alias glog='git log --oneline --graph --color --all --decorate'
# for WSL usage
alias powershell.exe='/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe'
alias powershell='/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe'
alias code='/mnt/c/Program\ Files/Microsoft\ VS\ Code/Code.exe'
alias code.exe='code'
alias codium='/mnt/c/Program\ Files/VSCodium/VSCodium.exe'
alias codium.exe='codium'
